### ISSUE TITLE
PluginError

### ISSUE THREAD

**Issue by lukelarsen** [ughitsaaron/gulp-styleguidejs#1]
I get this when running the gulp plugin
```
/node_modules/gulp-styleguidejs/index.js:42
      throw new PluginError(PLUGIN_NAME, err);
            ^
Error: undefined:1510:5: missing '}'
```

**Comment by ughitsaaron** [comment]
@lukelarsen Oh, no! Thanks for reporting this.

The error seems to be suggesting there's a missing closing bracket somewhere other than in the plugin itself? At 1510:5. Could that be in your gulpfile, perhaps?

**Comment by lukelarsen** [comment]
Not sure. I'll check it out. Thanks for getting back.

**Comment by lukelarsen** [comment]
You are correct. If I use this plugin like this:
```.pipe(styleguidejs())```
Everything is fine. If I try to add some options though I get the errors. I'm following the directions in the README. Could you show me an example of how to use options?
