### ISSUE TITLE
index.html wont save to gulp.dest()

### ISSUE THREAD

**Issue by msisto** [ughitsaaron/gulp-styleguidejs#3]
I cannot get `index.html` to save to `/docs`. It always saves to in the root path.

**from gulpfile.js:**
```
var styleguidejs  = require('gulp-styleguidejs');

gulp.task('docs', function() {
  gulp.src('./src/styles.css')
    .pipe(styleguidejs())
    .pipe(gulp.dest("./docs"))
});
```

**Comment by powerbuoy** [comment]
+1 I'm experiencing the same problem. The strange thing is it only happened after I moved my sass/ directory into a src/ subdirectory. When I had:
root/
root/sass/
root/dist/
All was good and index.html would end up in root/dist/, but once I moved root/sass/ inside root/src/sass/ index.html for some strange reason ends up in root/../dist/
How is this possible?

**Comment by ughitsaaron** [comment]
I'll take a look at this tomorrow! Apologies for the delay.

**Comment by powerbuoy** [comment]
Great news!
